/**
 */
package org.palladiosimulator.envdyn.environment.staticmodel.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import org.palladiosimulator.envdyn.environment.staticmodel.util.StaticmodelAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class StaticmodelItemProviderAdapterFactory extends StaticmodelAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public StaticmodelItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.envdyn.environment.staticmodel.GroundRandomVariable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GroundRandomVariableItemProvider groundRandomVariableItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.envdyn.environment.staticmodel.GroundRandomVariable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGroundRandomVariableAdapter() {
		if (groundRandomVariableItemProvider == null) {
			groundRandomVariableItemProvider = new GroundRandomVariableItemProvider(this);
		}

		return groundRandomVariableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.envdyn.environment.staticmodel.LocalProbabilisticModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LocalProbabilisticModelItemProvider localProbabilisticModelItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.envdyn.environment.staticmodel.LocalProbabilisticModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLocalProbabilisticModelAdapter() {
		if (localProbabilisticModelItemProvider == null) {
			localProbabilisticModelItemProvider = new LocalProbabilisticModelItemProvider(this);
		}

		return localProbabilisticModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.envdyn.environment.staticmodel.ProbabilisticModelRepository} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProbabilisticModelRepositoryItemProvider probabilisticModelRepositoryItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.envdyn.environment.staticmodel.ProbabilisticModelRepository}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createProbabilisticModelRepositoryAdapter() {
		if (probabilisticModelRepositoryItemProvider == null) {
			probabilisticModelRepositoryItemProvider = new ProbabilisticModelRepositoryItemProvider(this);
		}

		return probabilisticModelRepositoryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.envdyn.environment.staticmodel.GroundProbabilisticNetwork} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GroundProbabilisticNetworkItemProvider groundProbabilisticNetworkItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.envdyn.environment.staticmodel.GroundProbabilisticNetwork}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGroundProbabilisticNetworkAdapter() {
		if (groundProbabilisticNetworkItemProvider == null) {
			groundProbabilisticNetworkItemProvider = new GroundProbabilisticNetworkItemProvider(this);
		}

		return groundProbabilisticNetworkItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.envdyn.environment.staticmodel.LocalProbabilisticNetwork} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LocalProbabilisticNetworkItemProvider localProbabilisticNetworkItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.envdyn.environment.staticmodel.LocalProbabilisticNetwork}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLocalProbabilisticNetworkAdapter() {
		if (localProbabilisticNetworkItemProvider == null) {
			localProbabilisticNetworkItemProvider = new LocalProbabilisticNetworkItemProvider(this);
		}

		return localProbabilisticNetworkItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (groundRandomVariableItemProvider != null) groundRandomVariableItemProvider.dispose();
		if (localProbabilisticModelItemProvider != null) localProbabilisticModelItemProvider.dispose();
		if (probabilisticModelRepositoryItemProvider != null) probabilisticModelRepositoryItemProvider.dispose();
		if (groundProbabilisticNetworkItemProvider != null) groundProbabilisticNetworkItemProvider.dispose();
		if (localProbabilisticNetworkItemProvider != null) localProbabilisticNetworkItemProvider.dispose();
	}

}
