<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="environment" nsURI="http://palladiosimulator.org/Environment/1.0"
    nsPrefix="environment">
  <eSubpackages name="templatevariable" nsURI="http://palladiosimulator.org/Environment/TemplateVariable/1.0"
      nsPrefix="templatevariable">
    <eClassifiers xsi:type="ecore:EClass" name="TemplateVariableDefinitions" eSuperTypes="platform:/plugin/tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
          eType="#//templatevariable/TemplateVariable" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="factors" upperBound="-1"
          eType="#//templatevariable/TemplateFactor" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
          eType="#//templatevariable/Argument" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="relation" upperBound="-1"
          eType="#//templatevariable/Relation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="templateGroups" upperBound="-1"
          eType="#//templatevariable/TemplateVariableGroup" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateVariable" eSuperTypes="platform:/plugin/tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="shared" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="signature" lowerBound="1"
          upperBound="-1" eType="#//templatevariable/LogicalVariable" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="refines" eType="#//templatevariable/TemplateVariable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateFactor" abstract="true" eSuperTypes="platform:/plugin/tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="scope" lowerBound="1"
          upperBound="-1" eType="#//templatevariable/TemplateVariable"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="temporal" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Argument" eSuperTypes="platform:/plugin/tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity"/>
    <eClassifiers xsi:type="ecore:EClass" name="Relation" abstract="true"/>
    <eClassifiers xsi:type="ecore:EEnum" name="DependenceType">
      <eLiterals name="DIRECTED"/>
      <eLiterals name="UNDIRECTED" value="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProbabilisticTemplateFactor" eSuperTypes="#//templatevariable/TemplateFactor">
      <eStructuralFeatures xsi:type="ecore:EReference" name="distributionFamily" lowerBound="1"
          eType="ecore:EClass ../../tools.mdsd.probdist.model/model/probdist.ecore#//distributiontype/ProbabilityDistributionSkeleton"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DependenceRelation" eSuperTypes="#//templatevariable/Relation">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="#//templatevariable/DependenceType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="#//templatevariable/TemplateVariable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
          eType="#//templatevariable/TemplateVariable"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="contingent" lowerBound="1"
          eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemporalRelation" abstract="true"
        eSuperTypes="#//templatevariable/Relation platform:/plugin/tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//NamedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="PersistenceRelation" eSuperTypes="#//templatevariable/TemporalRelation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="interfaceVariable" lowerBound="1"
          eType="#//templatevariable/TemplateVariable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TimeSliceRelation" eSuperTypes="#//templatevariable/TemporalRelation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
          eType="#//templatevariable/TemplateVariable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="#//templatevariable/TemplateVariable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateVariableGroup" eSuperTypes="platform:/plugin/tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="groupedTemplates" lowerBound="1"
          upperBound="-1" eType="#//templatevariable/TemplateVariable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LogicalVariable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="argument" lowerBound="1"
          eType="#//templatevariable/Argument"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="staticmodel" nsURI="http://palladiosimulator.org/Environment/StaticModel/1.0"
      nsPrefix="staticmodel">
    <eClassifiers xsi:type="ecore:EClass" name="GroundRandomVariable" eSuperTypes="platform:/plugin/tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="instantiatedTemplate"
          lowerBound="1" eType="#//templatevariable/TemplateVariable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dependenceStructure"
          lowerBound="1" upperBound="-1" eType="#//templatevariable/DependenceRelation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="descriptiveModel" lowerBound="1"
          eType="#//staticmodel/GroundProbabilisticModel"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="appliedObjects" lowerBound="1"
          upperBound="-1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GroundProbabilisticModel" eSuperTypes="platform:/plugin/tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="instantiatedFactor" lowerBound="1"
          eType="#//templatevariable/TemplateFactor"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="distribution" lowerBound="1"
          eType="ecore:EClass ../../tools.mdsd.probdist.model/model/probdist.ecore#//distributionfunction/ProbabilityDistribution"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProbabilisticModelRepository" eSuperTypes="platform:/plugin/tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="models" upperBound="-1"
          eType="#//staticmodel/GroundProbabilisticNetwork" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GroundProbabilisticNetwork" eSuperTypes="platform:/plugin/tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="localModels" lowerBound="1"
          upperBound="-1" eType="#//staticmodel/GroundProbabilisticModel" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="localProbabilisticModels"
          lowerBound="1" upperBound="-1" eType="#//staticmodel/LocalProbabilisticNetwork"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LocalProbabilisticNetwork">
      <eStructuralFeatures xsi:type="ecore:EReference" name="groundRandomVariables"
          lowerBound="1" upperBound="-1" eType="#//staticmodel/GroundRandomVariable"
          containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="dynamicmodel" nsURI="http://palladiosimulator.org/Environment/DynamicModel/1.0"
      nsPrefix="dynamicmodel">
    <eClassifiers xsi:type="ecore:EClass" name="DynamicBehaviourRepository" eSuperTypes="platform:/plugin/tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="extensions" upperBound="-1"
          eType="#//dynamicmodel/DynamicBehaviourExtension" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DynamicBehaviourExtension" eSuperTypes="platform:/plugin/tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1"
          eType="#//staticmodel/GroundProbabilisticNetwork"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="behaviour" lowerBound="1"
          eType="#//dynamicmodel/DynamicBehaviour" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DynamicBehaviour" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="localModels" lowerBound="1"
          upperBound="-1" eType="#//dynamicmodel/TemporalDynamic" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InductiveDynamicBehaviour" eSuperTypes="#//dynamicmodel/DynamicBehaviour">
      <eStructuralFeatures xsi:type="ecore:EReference" name="timeSliceInductions"
          lowerBound="1" upperBound="-1" eType="#//dynamicmodel/TimeSliceInduction"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InterTimeSliceInduction" eSuperTypes="#//dynamicmodel/TimeSliceInduction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="temporalStructure" lowerBound="1"
          upperBound="-1" eType="#//templatevariable/TemporalRelation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntraTimeSliceInduction" eSuperTypes="#//dynamicmodel/TimeSliceInduction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="dependenceStructure"
          lowerBound="1" upperBound="-1" eType="#//templatevariable/DependenceRelation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemporalDynamic" eSuperTypes="platform:/plugin/tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="instantiatedFactor" lowerBound="1"
          eType="#//templatevariable/TemplateFactor"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="distributionFunction"
          lowerBound="1" eType="ecore:EClass ../../tools.mdsd.probdist.model/model/probdist.ecore#//distributionfunction/ProbabilityDistribution"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TimeSliceInduction" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="descriptiveModel" lowerBound="1"
          eType="#//dynamicmodel/TemporalDynamic"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="appliedGroundVariable"
          lowerBound="1" eType="#//staticmodel/GroundRandomVariable"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
