/**
 *
 * $Id$
 */
package org.palladiosimulator.envdyn.environment.templatevariable.validation;

import org.palladiosimulator.envdyn.environment.templatevariable.DependenceType;
import org.palladiosimulator.envdyn.environment.templatevariable.TemplateVariable;

/**
 * A sample validator interface for {@link org.palladiosimulator.envdyn.environment.templatevariable.DependenceRelation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DependenceRelationValidator {
	boolean validate();

	boolean validateType(DependenceType value);
	boolean validateTarget(TemplateVariable value);
	boolean validateSource(TemplateVariable value);
	boolean validateContingent(boolean value);
}
