/**
 *
 * $Id$
 */
package org.palladiosimulator.envdyn.environment.templatevariable.validation;

import tools.mdsd.probdist.distributiontype.ProbabilityDistributionSkeleton;

/**
 * A sample validator interface for {@link org.palladiosimulator.envdyn.environment.templatevariable.ProbabilisticTemplateFactor}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProbabilisticTemplateFactorValidator {
	boolean validate();

	boolean validateDistributionFamily(ProbabilityDistributionSkeleton value);
}
