/**
 *
 * $Id$
 */
package org.palladiosimulator.envdyn.environment.templatevariable.validation;

import org.eclipse.emf.common.util.EList;

import org.palladiosimulator.envdyn.environment.templatevariable.Argument;
import org.palladiosimulator.envdyn.environment.templatevariable.Relation;
import org.palladiosimulator.envdyn.environment.templatevariable.TemplateFactor;
import org.palladiosimulator.envdyn.environment.templatevariable.TemplateVariable;
import org.palladiosimulator.envdyn.environment.templatevariable.TemplateVariableGroup;

/**
 * A sample validator interface for {@link org.palladiosimulator.envdyn.environment.templatevariable.TemplateVariableDefinitions}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TemplateVariableDefinitionsValidator {
	boolean validate();

	boolean validateVariables(EList<TemplateVariable> value);
	boolean validateFactors(EList<TemplateFactor> value);
	boolean validateArguments(EList<Argument> value);
	boolean validateRelation(EList<Relation> value);
	boolean validateTemplateGroups(EList<TemplateVariableGroup> value);
}
