/**
 *
 * $Id$
 */
package org.palladiosimulator.envdyn.environment.dynamicmodel.validation;

import org.palladiosimulator.envdyn.environment.dynamicmodel.DynamicBehaviour;

import org.palladiosimulator.envdyn.environment.staticmodel.GroundProbabilisticNetwork;

/**
 * A sample validator interface for {@link org.palladiosimulator.envdyn.environment.dynamicmodel.DynamicBehaviourExtension}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DynamicBehaviourExtensionValidator {
	boolean validate();

	boolean validateGroundNetwork(GroundProbabilisticNetwork value);
	boolean validateBehaviour(DynamicBehaviour value);
}
