/**
 *
 * $Id$
 */
package org.palladiosimulator.envdyn.environment.dynamicmodel.validation;

import org.palladiosimulator.envdyn.environment.templatevariable.TemplateFactor;

import tools.mdsd.probdist.distributionfunction.ProbabilityDistribution;

/**
 * A sample validator interface for {@link org.palladiosimulator.envdyn.environment.dynamicmodel.TemporalDynamic}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TemporalDynamicValidator {
	boolean validate();

	boolean validateInstantiatedFactor(TemplateFactor value);
	boolean validateDistribution(ProbabilityDistribution value);
}
