/**
 *
 * $Id$
 */
package org.palladiosimulator.envdyn.environment.staticmodel.validation;

import org.eclipse.emf.common.util.EList;

import org.palladiosimulator.envdyn.environment.staticmodel.LocalProbabilisticModel;
import org.palladiosimulator.envdyn.environment.staticmodel.LocalProbabilisticNetwork;

/**
 * A sample validator interface for {@link org.palladiosimulator.envdyn.environment.staticmodel.GroundProbabilisticNetwork}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GroundProbabilisticNetworkValidator {
	boolean validate();

	boolean validateLocalModels(EList<LocalProbabilisticModel> value);
	boolean validateLocalNetworks(EList<LocalProbabilisticNetwork> value);
}
